Repository 2025-Advanced-Capstone-LifelineWatch/backend, pull requests merged in 2025-05, with the labels that each got.

#27 fcm토큰 관련하여 수정
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthController.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/user/entity/User.java
Labels: Feature ✨

#29 Refactor: 회원가입 및 노인 할당시 채팅방 자동 생성 #28
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/notification/controller/HealthCheckController.java
  src/main/java/com/kgu/life_watch/domain/user/controller/UserController.java
  src/main/java/com/kgu/life_watch/domain/user/service/UserService.java
Labels: Feature ✨, Refactor ♻️

#30 수정 및 기능 추가 요구 구현
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthController.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/ElderlySignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/LoginResponse.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/notification/controller/AlarmController.java
  src/main/java/com/kgu/life_watch/domain/notification/service/MedicineAlarmService.java
  src/main/java/com/kgu/life_watch/domain/user/entity/ElderlyProfile.java
  src/main/java/com/kgu/life_watch/domain/user/entity/User.java
Labels: Refactor ♻️

#31 요구사항 수정했슈
  src/main/java/com/kgu/life_watch/domain/auth/dto/ElderlySignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/LoginResponse.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/global/config/SecurityConfig.java
Labels: Refactor ♻️

#32 Refactor: 사회복지사 회원 가입시 request에 인증코드 삭제 (#5)
  src/main/java/com/kgu/life_watch/domain/auth/dto/SocialWorkerSignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
Labels: Refactor ♻️

#34 영속성 관련 수정
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthSmsService.java
  src/main/java/com/kgu/life_watch/domain/auth/service/PasswordService.java
  src/main/java/com/kgu/life_watch/domain/user/repository/UserRepository.java
Labels: Refactor ♻️

#35 fcmtoken 업데이트 로직 구현이요 + ApiResponse
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthController.java
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthPasswordController.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/FcmTokenUpdateRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
Labels: Feature ✨, Refactor ♻️

#36 Refactor: 기타 리팩토링
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthController.java
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthPasswordController.java
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthSmsController.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/PasswordChangeRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/ElderlySignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/FcmTokenUpdateRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/FindIdRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/FindPasswordRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/PasswordChangeRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/ResetPasswordRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/SmsVerificationRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/SocialWorkerSignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/response/FindLoginIdResponse.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/response/SmsVerifyResponse.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/auth/service/PasswordService.java
  src/main/java/com/kgu/life_watch/domain/notification/controller/AlarmController.java
  src/main/java/com/kgu/life_watch/domain/notification/dto/MedicineAlarmRequest.java
  src/main/java/com/kgu/life_watch/domain/notification/service/MedicineAlarmService.java
  src/main/java/com/kgu/life_watch/domain/user/entity/SocialWorkerProfile.java
Labels: Refactor ♻️

#37 반복되는 알람 구조로 변경 + 하루에 여러번 먹어야 하는 약들 같은 경우 그룹으로 따로처리
  src/main/java/com/kgu/life_watch/LifeWatchApplication.java
  src/main/java/com/kgu/life_watch/domain/notification/controller/AlarmController.java
  src/main/java/com/kgu/life_watch/domain/notification/controller/AlarmGroupController.java
  src/main/java/com/kgu/life_watch/domain/notification/dto/AlarmGroupDto.java
  src/main/java/com/kgu/life_watch/domain/notification/dto/MedicineAlarmDto.java
  src/main/java/com/kgu/life_watch/domain/notification/dto/MedicineAlarmRequest.java
  src/main/java/com/kgu/life_watch/domain/notification/entity/AlarmGroup.java
  src/main/java/com/kgu/life_watch/domain/notification/entity/MedicineAlarm.java
  src/main/java/com/kgu/life_watch/domain/notification/repository/AlarmGroupRepository.java
  src/main/java/com/kgu/life_watch/domain/notification/repository/MedicineAlarmRepository.java
  src/main/java/com/kgu/life_watch/domain/notification/scheduler/MedicineAlarmScheduler.java
  src/main/java/com/kgu/life_watch/domain/notification/service/AlarmGroupService.java
  src/main/java/com/kgu/life_watch/domain/notification/service/FirebaseMessageService.java
  src/main/java/com/kgu/life_watch/domain/notification/service/MedicineAlarmService.java
Labels: Feature ✨, Refactor ♻️

#38 fcmtoken을 헤더로 보내는 거에서 바디로 보내는걸로 변경
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthController.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/ElderlySignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/SocialWorkerSignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
Labels: Refactor ♻️

#39 개인 정보 수정 구현하기
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/UserUpdateRequest.java
  src/main/java/com/kgu/life_watch/domain/user/controller/UserController.java
  src/main/java/com/kgu/life_watch/domain/user/entity/ElderlyProfile.java
  src/main/java/com/kgu/life_watch/domain/user/entity/User.java
  src/main/java/com/kgu/life_watch/domain/user/service/UserService.java
Labels: Feature ✨

#40 Refactor: 인증을 위해 Long userId -> CustomUserDetails userDetails로 변경 (#5)
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthController.java
  src/main/java/com/kgu/life_watch/domain/user/controller/UserController.java
Labels: Refactor ♻️

#43 노인 회원가입시에 사회복지사 필수 할당 없애기
  src/main/java/com/kgu/life_watch/domain/auth/dto/request/ElderlySignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
Labels: Feature ✨, Refactor ♻️

#44 노인 할당 해제시에 아예 삭제되는 거 방지하기
  src/main/java/com/kgu/life_watch/domain/user/entity/SocialWorkerProfile.java
  src/main/java/com/kgu/life_watch/domain/user/entity/User.java
Labels: Refactor ♻️

#46 Refactor : 위험 알람 보낼 때 user.id를 넘기도록 변경 (5)
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/notification/service/FirebaseMessageService.java
  src/main/java/com/kgu/life_watch/domain/user/repository/ElderlyProfileRepository.java
Labels: Refactor ♻️

#45 로그인 시에 사회복지사 할당 안되어있어도 로그인되게 수정하기
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
Labels: Refactor ♻️

#47 위험 알람 경고시 몇분후에 없어지는 거 방지
  src/main/java/com/kgu/life_watch/domain/notification/controller/AlertController.java
  src/main/java/com/kgu/life_watch/domain/notification/entity/NotificationLog.java
  src/main/java/com/kgu/life_watch/domain/notification/repository/NotificationLogRepository.java
  src/main/java/com/kgu/life_watch/domain/notification/service/FirebaseMessageService.java
Labels: Feature ✨, Refactor ♻️

#49 Refactor: 노인 할당/할당해제시 채팅방 생성 관련 로직 수정 (#28)
  src/main/java/com/kgu/life_watch/domain/chat/entity/ChatRoom.java
  src/main/java/com/kgu/life_watch/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/kgu/life_watch/domain/chat/service/ChatMessageService.java
  src/main/java/com/kgu/life_watch/domain/chat/service/ChatRoomService.java
  src/main/java/com/kgu/life_watch/domain/user/service/UserService.java
Labels: Refactor ♻️

#51 백엔드에서도 인증번호 인증된 휴대폰 받도록
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthSmsService.java
  src/main/java/com/kgu/life_watch/global/exception/ErrorCode.java
Labels: Feature ✨

#53 LazyInitializationException 해결
  src/main/java/com/kgu/life_watch/domain/notification/repository/MedicineAlarmRepository.java
Labels: Refactor ♻️

#54 로그인시에 휴대폰번호 및 주소도 반환되게
  src/main/java/com/kgu/life_watch/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
Labels: Feature ✨

#59 로그 넣었던거랑 쿼리문 조금 수정한 거 올려요
  src/main/java/com/kgu/life_watch/domain/notification/repository/MedicineAlarmRepository.java
  src/main/java/com/kgu/life_watch/domain/notification/scheduler/MedicineAlarmScheduler.java
  src/main/java/com/kgu/life_watch/domain/notification/service/FirebaseMessageService.java
Labels: Feature ✨, Refactor ♻️

#60 복용량 추가했습니두
  src/main/java/com/kgu/life_watch/domain/notification/dto/MedicineAlarmDto.java
  src/main/java/com/kgu/life_watch/domain/notification/dto/MedicineAlarmRequest.java
  src/main/java/com/kgu/life_watch/domain/notification/entity/MedicineAlarm.java
  src/main/java/com/kgu/life_watch/domain/notification/service/AlarmGroupService.java
  src/main/java/com/kgu/life_watch/domain/notification/service/FirebaseMessageService.java
Labels: Feature ✨

#62 약 복용개수 리스트로 변경
  src/main/java/com/kgu/life_watch/domain/notification/dto/MedicineAlarmDto.java
  src/main/java/com/kgu/life_watch/domain/notification/dto/MedicineAlarmRequest.java
  src/main/java/com/kgu/life_watch/domain/notification/entity/MedicineAlarm.java
  src/main/java/com/kgu/life_watch/domain/notification/service/AlarmGroupService.java
Labels: Feature ✨
