Repository 2025-Advanced-Capstone-LifelineWatch/backend, pull requests merged in 2025-04, with the labels that each got.

#4 Feat : 회원가입기능 구현 #3
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthController.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/SignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/SocialWorkerSignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/user/entity/User.java
  src/main/java/com/kgu/life_watch/domain/user/repository/UserRepository.java
  src/main/java/com/kgu/life_watch/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: Feature ✨

#7 Chore: 초기 세팅 추가
  build.gradle
  scripts/pre-commit
  src/main/java/com/kgu/life_watch/LifeWatchApplication.java
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthController.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/ElderlySignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/LoginRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/SocialWorkerSignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/user/controller/UserController.java
  src/main/java/com/kgu/life_watch/domain/user/entity/ElderlyProfile.java
  src/main/java/com/kgu/life_watch/domain/user/entity/SocialWorkerProfile.java
  src/main/java/com/kgu/life_watch/domain/user/entity/User.java
  src/main/java/com/kgu/life_watch/domain/user/repository/UserRepository.java
  src/main/java/com/kgu/life_watch/global/config/SecurityConfig.java
  src/main/java/com/kgu/life_watch/global/config/SwaggerConfig.java
  src/main/java/com/kgu/life_watch/global/domain/BaseEntity.java
  src/main/java/com/kgu/life_watch/global/domain/SuccessCode.java
  src/main/java/com/kgu/life_watch/global/dto/response/ApiResponse.java
  src/main/java/com/kgu/life_watch/global/exception/ErrorCode.java
  src/main/java/com/kgu/life_watch/global/exception/LifelineException.java
  src/main/java/com/kgu/life_watch/global/filter/FilterExceptionHandler.java
  src/main/java/com/kgu/life_watch/global/handler/GlobalExceptionHandler.java
  src/main/java/com/kgu/life_watch/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/kgu/life_watch/global/jwt/JwtTokenProvider.java
  src/main/java/com/kgu/life_watch/global/security/CustomUserDetails.java
  src/main/java/com/kgu/life_watch/global/security/CustomUserDetailsService.java
  src/main/resources/application.yml
  src/test/java/com/kgu/life_watch/LifeWatchApplicationTests.java
Labels: Chore ⚙️, Database 🗃️

#9 Feat: 실시간 채팅 기능 구현 (#8)
  build.gradle
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/chat/controller/ChatMessageController.java
  src/main/java/com/kgu/life_watch/domain/chat/controller/ChatRoomController.java
  src/main/java/com/kgu/life_watch/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/kgu/life_watch/domain/chat/dto/response/ChatMessageResponse.java
  src/main/java/com/kgu/life_watch/domain/chat/dto/response/ChatRoomResponse.java
  src/main/java/com/kgu/life_watch/domain/chat/entity/ChatMessage.java
  src/main/java/com/kgu/life_watch/domain/chat/entity/ChatRoom.java
  src/main/java/com/kgu/life_watch/domain/chat/entity/RoomStatus.java
  src/main/java/com/kgu/life_watch/domain/chat/entity/mapping/ChatParticipation.java
  src/main/java/com/kgu/life_watch/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/kgu/life_watch/domain/chat/repository/ChatParticipationRepository.java
  src/main/java/com/kgu/life_watch/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/kgu/life_watch/domain/chat/service/ChatMessageService.java
  src/main/java/com/kgu/life_watch/domain/chat/service/ChatParticipationService.java
  src/main/java/com/kgu/life_watch/domain/chat/service/ChatRoomService.java
  src/main/java/com/kgu/life_watch/domain/user/entity/User.java
  src/main/java/com/kgu/life_watch/domain/user/repository/ElderlyProfileRepository.java
  src/main/java/com/kgu/life_watch/domain/user/repository/SocialWorkerProfileRepository.java
  src/main/java/com/kgu/life_watch/global/config/SecurityConfig.java
  src/main/java/com/kgu/life_watch/global/config/WebSocketConfig.java
  src/main/java/com/kgu/life_watch/global/handler/StompHandler.java
Labels: Feature ✨, Refactor ♻️

#11 Refactor: 회원가입 로직 수정
  src/main/java/com/kgu/life_watch/domain/auth/dto/SocialWorkerSignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/user/entity/ElderlyProfile.java
  src/main/java/com/kgu/life_watch/domain/user/entity/SocialWorkerProfile.java
Labels: Refactor ♻️

#14 알람 기능을 구현한다.
  .gitignore
  build.gradle
  src/main/java/com/kgu/life_watch/domain/notification/config/FirebaseConfig.java
  src/main/java/com/kgu/life_watch/domain/notification/controller/AlertController.java
  src/main/java/com/kgu/life_watch/domain/notification/dto/EmergencyAlertRequest.java
  src/main/java/com/kgu/life_watch/domain/notification/service/FirebaseMessageService.java
  src/main/java/com/kgu/life_watch/domain/user/entity/SocialWorkerProfile.java
  src/main/java/com/kgu/life_watch/domain/user/repository/ElderlyProfileRepository.java
Labels: Feature ✨, Refactor ♻️

#18 약 알람 기능 추가 구현을 하였음
  src/main/java/com/kgu/life_watch/domain/notification/controller/AlarmController.java
  src/main/java/com/kgu/life_watch/domain/notification/dto/MedicineAlarmDto.java
  src/main/java/com/kgu/life_watch/domain/notification/dto/MedicineAlarmRequest.java
  src/main/java/com/kgu/life_watch/domain/notification/entity/MedicineAlarm.java
  src/main/java/com/kgu/life_watch/domain/notification/repository/MedicineAlarmRepository.java
  src/main/java/com/kgu/life_watch/domain/notification/scheduler/MedicineAlarmScheduler.java
  src/main/java/com/kgu/life_watch/domain/notification/service/FirebaseMessageService.java
  src/main/java/com/kgu/life_watch/domain/notification/service/MedicineAlarmService.java
  src/main/java/com/kgu/life_watch/domain/user/entity/SocialWorkerProfile.java
  src/main/java/com/kgu/life_watch/domain/user/entity/User.java
  src/main/java/com/kgu/life_watch/domain/user/repository/ElderlyProfileRepository.java
  src/main/java/com/kgu/life_watch/global/exception/ErrorCode.java
Labels: Feature ✨, Refactor ♻️

#16 Refactor: SimpleBroker -> RabbitMQ 도입 완료 #15
  build.gradle
  docker-compose.yml
  src/main/java/com/kgu/life_watch/domain/chat/controller/ChatMessageController.java
  src/main/java/com/kgu/life_watch/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/kgu/life_watch/domain/chat/service/ChatMessageService.java
  src/main/java/com/kgu/life_watch/domain/user/controller/UserController.java
  src/main/java/com/kgu/life_watch/domain/user/dto/UserProfileResponse.java
  src/main/java/com/kgu/life_watch/domain/user/entity/SocialWorkerProfile.java
  src/main/java/com/kgu/life_watch/domain/user/service/UserService.java
  src/main/java/com/kgu/life_watch/global/config/RabbitConfig.java
  src/main/java/com/kgu/life_watch/global/config/WebSocketConfig.java
  src/main/resources/application.yml
Labels: Refactor ♻️

#20 sms 인증 기능을 구현하였음
  build.gradle
  src/main/java/com/kgu/life_watch/domain/auth/controller/AuthSmsController.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/ElderlySignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/SmsVerificationRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/dto/SocialWorkerSignUpRequest.java
  src/main/java/com/kgu/life_watch/domain/auth/entity/SmsVerification.java
  src/main/java/com/kgu/life_watch/domain/auth/repository/SmsVerificationRepository.java
  src/main/java/com/kgu/life_watch/domain/auth/scheduler/AuthSmsCleanupScheduler.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthService.java
  src/main/java/com/kgu/life_watch/domain/auth/service/AuthSmsService.java
  src/main/java/com/kgu/life_watch/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: Chore ⚙️, Feature ✨
